algoritmo "Desvio de Fluxo de Dados"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]

var

professor: caractere
aluno: caractere
reserva: caractere

inicio

professor <- "Julio"
aluno <- "Ricardo"
reserva
escreva("Olá professor, insira o seu nome: ")

escreval("Corrigindo, o nome do aluno é ",professor,", e o nome do professor é ",aluno,"!")


fimalgoritmo