algoritmo "Simulador de Inventário"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]

var

item: caractere
item2: caractere


inicio

escreva("Digite o item a ser registrado: ")
leia(item)
escreval("Item 1: ",item,", registrado com sucesso!")
escreva("Digite o proximo item a ser registrado: ")
leia(item)
escreval("Item 1 descartado, item 2 registrado com sucesso --->> ",item)


fimalgoritmo