algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]

var

altura: inteiro
largura: inteiro
perimetro: caractere
area: caractere
inicio

escreva("Informe a LARGURA: ")
leia(largura)
escreva("Informe a ALTURA: ")
leia(altura)
area <- largura * altura
perimetro <- 2 * (largura + altura)
escreval("A area total da sala é ",area," e seu perímetro é ",perimetro,"!")


fimalgoritmo