algoritmo "A Catraca do Laboratório"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]

var

idade: inteiro


inicio

    escreva("Insira sua idade: ")
    leia(idade)
        se (idade >= 18) entao
            escreval("ACESSO LIBERADO: Máquina Habilitada")
        senao
            escreval("ACESSO NEGADO: Risco de Segurança. Procure seu Professor.")
        fimse

        


fimalgoritmo